name: Nightly Release

on:
  schedule:
    - cron: '0 8 * * *' # Daily at 8 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  nightly:
    name: Nightly Build & Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor || github.event_name == 'workflow_dispatch'
    
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Setup Git user
      uses: fregante/setup-git-user@v2
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: pnpm run test:run
      
    - name: Build packages
      run: pnpm run build
      
    - name: Deploy nightly
      run: pnpm run deploy-nightly
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
